databases:
  - name: ngo_db
    databaseName: homefinder
    user: postgres

services:
  - type: web
    name: ngo-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn core.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ngo_db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
    postDeployCommand: |
      python manage.py makemigrations
      python manage.py migrate
